service: project-task-graphql
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev

functions:
  hello:
    handler: dist/hello.bootstrap
    events:
      - http:
          path: hello
          method: GET
          cors: true
